# Generated by Django 2.2.4 on 2019-09-19 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190918_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='firstimage',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
